# Generated by Django 5.0.1 on 2025-01-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("username", models.CharField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("full_name", models.CharField(max_length=255)),
                ("height", models.FloatField()),
                ("weight", models.FloatField()),
                ("gender", models.CharField(max_length=10)),
            ],
        ),
    ]
