# Generated by Django 5.0.1 on 2025-01-13 15:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="full_name",
            new_name="fullName",
        ),
    ]
