# Generated by Django 5.0.1 on 2025-01-14 11:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0003_userprofile_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
    ]
